### ISSUE TITLE
AMQ: Can't run same suite of tests on the same openshift instance

### ISSUE THREAD

**Issue by jwendell** [jboss-openshift/ce-testsuite#149]
If they use routes.

"For two or more routes that claim the same host name, the resolution order is based on the age of the route and the oldest route would win the claim to that host." Taken from the docs: https://docs.openshift.com/container-platform/3.3/architecture/core_concepts/routes.html#router-sharding

It doesn't matter if the duplicated routes are in different namespaces...

AmqExternalAccessTest makes use of a local resources/amq-routes.json, which defines the templates using hardcoded hostnames. They should be dynamic generated, to avoid this issue.

**Comment by rimolive** [comment]
Actually the problem is that the A-MQ templates lack of the Route definitions. That happen because we initially don't support expose these ports externally, but in fact this can be done. That's the main reason I have those hardcoded routes.

Unless ce-arq has a specific method to expose services (by generating a dynamic route), I don't see other way to avoid do that.

**Comment by jwendell** [comment]
I believe you can have the routes, just don't specify a hostname. Openshift will generate a random one. That's what templates are doing.

"If a host name is not provided as part of the route definition, then OpenShift Container Platform automatically generates one for you"

See https://docs.openshift.com/container-platform/3.3/architecture/core_concepts/routes.html#route-hostnames
